# Generated by Django 5.2.18 on 2026-10-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(help_text='e.g., image, document', max_length=50)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, help_text='Username of uploader', max_length=150)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for images', max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'media file',
                'verbose_name_plural': 'media files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='content_type',
            field=models.CharField(choices=[('desk', 'Desk'), ('person', 'Person'), ('enquiry', 'Enquiry'), ('cluster', 'Cluster'), ('content', 'Content'), ('setting', 'Setting'), ('siteinfo', 'Siteinfo'), ('media', 'Media')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='section',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
